//Creazione dell'array con la lista della spesa
const listaSpesa = [
    "pane",
    "insalata",
    "mandarini",
    "frutta",
    "lattuga",
    "manico della scopa",
    "olive",
    "piadine",
    "cotto",
    "speck",
    "farina",
    "salame",
    "carciofi",
    "asparagi",
    "olio",
    "sgrassatore",
    "dentifircio",
    "tabacco",
    "pepe",
    "carne",
    "coltello piccolo",
    "patatine",
    "spazzolini",
    "ammorbidente"
]